name = "GridSide"
license = "MIT"
licenselink = "https://github.com/chipsenkbeil/grid-side/blob/master/LICENSE.md"
description = "Personal portfolio, blog, and gallery for use by the Hugo generator."
homepage = "https://github.com/chipsenkbeil/grid-side"
tags = ["blog", "portfolio", "projects"]
features = ["blog", "portfolio", "gallery"]
min_version = 0.14

[author]
    name = "Chip Senkbeil"
    homepage = "https://chipsenkbeil.com/"

